package RecapJavaWithAhmet;

public class MAP {
    //POSSIBLE INTERVIEW QUESTIONS:
    //1) CAN YOU TELL ME ABOUT MAP AND WHY DO YOU USE MAP IN YOUR PROJECT?
    //2)WHAT IS THE CONNECTION BETWEEN MAP AND COLLECTION?
    //3) WHAT IS THE TYPE OF MAP AND DIFFERENCE BETWEEN THEM?
    //4*****)WHAT IS THE DIFFERENCE BETWEEN HASHMAP AND HASHTABLE?

    //MAP IS THE WAY OF STORING DATA AS A KEY AND VALUE FORMAT.
    // I LOVE USING MAP IN MY PROJECT BECAUSE IT HAS KEY AND VALUE FORMAT
    //WHICH IS GOOD FOR MY PROJECT TO STORE LIKE CUSTOMER NAME WITH BALANCE
    //2) MAP<KEY,VALUE> KEY ONLY STORES THE UNIQUE VALUE WHICH MEANS IT IS
    //ACTING LIKE SET
    //2*)VALUE MAY OR NOT STORE DUPLICATES AS A VALUE WHICH MEANS IT IS
    //ACTING LIKE LIST
    //3)HASHMAP --> randomly stores
    //3*)LINKHASHMAP--> insertion order
    //3**)TREEMAP-->ascending order

    //(***********))
    //THE MAIN DIFFERENCE is THREAD-SAFE(SYNCHRONIZED)
        //FIRST COME FIRST SERVE
    //IT MEANS THE SYSTEM WILL **WAIT** UNTIL THE ACTION IS DONE THEN
    //IT WILL CONTINUE FOR THE NEXT ACTIONS






}
